-- ==============================================================================
-- Migration: 20260820100000_update_accurate_items_for_shop_api.sql
-- Description: Schema for Accurate / Shop Items sync from VPS Shop API
-- ==============================================================================

-- 1. Create table if not exists (base schema)
create table if not exists accurate_items (
  id bigint primary key generated by default as identity,
  item_no text not null unique,
  item_name text,
  unit_name text default 'Pcs',
  unit_price numeric default 0,
  stock_quantity numeric default 0,
  available_to_sell numeric default 0,
  category text,
  brand text default 'SIEMENS',
  specs jsonb default '{}'::jsonb,
  source text default 'SHOP_API',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 2. Add all Shop API specific fields if they do not exist
alter table accurate_items 
  add column if not exists shop_id text,
  add column if not exists accurate_id bigint,
  add column if not exists sku text,
  add column if not exists description text,
  add column if not exists long_description text,
  add column if not exists base_price numeric default 0,
  add column if not exists stock_status text default 'INDENT',
  add column if not exists indent_time text,
  add column if not exists item_type text default 'INVENTORY',
  add column if not exists is_visible boolean default true,
  add column if not exists status text default 'APPROVED',
  add column if not exists image text,
  add column if not exists slider_images jsonb default '[]'::jsonb,
  add column if not exists datasheet text,
  add column if not exists specifications jsonb default '{}'::jsonb,
  add column if not exists meta_title text,
  add column if not exists meta_description text,
  add column if not exists shop_created_at timestamp with time zone,
  add column if not exists shop_updated_at timestamp with time zone,
  add column if not exists synced_at timestamp with time zone default now();

-- 3. Create or update indexes for high-speed search and filtering
create index if not exists idx_accurate_items_item_no on accurate_items (item_no);
create index if not exists idx_accurate_items_sku on accurate_items (sku);
create index if not exists idx_accurate_items_shop_id on accurate_items (shop_id);
create index if not exists idx_accurate_items_accurate_id on accurate_items (accurate_id);
create index if not exists idx_accurate_items_category on accurate_items (category);
create index if not exists idx_accurate_items_brand on accurate_items (brand);
create index if not exists idx_accurate_items_stock_status on accurate_items (stock_status);
create index if not exists idx_accurate_items_is_visible on accurate_items (is_visible);

-- Full-Text Search GIN Index (item_no, sku, item_name, category, brand, description)
drop index if exists idx_accurate_items_search;
create index idx_accurate_items_search on accurate_items using gin(
  to_tsvector('english', 
    coalesce(item_no, '') || ' ' || 
    coalesce(sku, '') || ' ' || 
    coalesce(item_name, '') || ' ' || 
    coalesce(category, '') || ' ' || 
    coalesce(brand, '') || ' ' ||
    coalesce(description, '')
  )
);

-- 4. Enable RLS (Row Level Security)
alter table accurate_items enable row level security;

-- Policies for accurate_items
drop policy if exists "Allow read access for all users on accurate_items" on accurate_items;
drop policy if exists "Allow read access for authenticated users on accurate_items" on accurate_items;
create policy "Allow read access for authenticated users on accurate_items" 
  on accurate_items for select using (auth.role() = 'authenticated');

drop policy if exists "Allow write access for authenticated users on accurate_items" on accurate_items;
create policy "Allow write access for authenticated users on accurate_items" 
  on accurate_items for all using (auth.role() = 'authenticated');

-- 5. Helper Function: Upsert batch items from Shop API
create or replace function upsert_shop_products(products_json jsonb)
returns integer
language plpgsql
security definer
as $$
declare
  inserted_count integer := 0;
begin
  insert into accurate_items (
    shop_id,
    item_no,
    sku,
    item_name,
    description,
    long_description,
    unit_price,
    base_price,
    available_to_sell,
    brand,
    category,
    image,
    slider_images,
    accurate_id,
    item_type,
    is_visible,
    status,
    datasheet,
    specifications,
    meta_title,
    meta_description,
    indent_time,
    stock_status,
    shop_created_at,
    shop_updated_at,
    source,
    synced_at,
    updated_at
  )
  select
    elem->>'id' as shop_id,
    coalesce(elem->>'sku', elem->>'item_no') as item_no,
    elem->>'sku' as sku,
    coalesce(elem->>'name', elem->>'item_name') as item_name,
    elem->>'description' as description,
    elem->>'longDescription' as long_description,
    coalesce((elem->>'price')::numeric, (elem->>'unit_price')::numeric, 0) as unit_price,
    coalesce((elem->>'basePrice')::numeric, (elem->>'price')::numeric, 0) as base_price,
    coalesce((elem->>'availableToSell')::numeric, (elem->>'stock_quantity')::numeric, 0) as available_to_sell,
    coalesce(elem->>'brand', 'SIEMENS') as brand,
    coalesce(elem->>'category', 'OTHER') as category,
    elem->>'image' as image,
    coalesce(elem->'sliderImages', '[]'::jsonb) as slider_images,
    (elem->>'accurateId')::bigint as accurate_id,
    coalesce(elem->>'itemType', 'INVENTORY') as item_type,
    coalesce((elem->>'isVisible')::boolean, true) as is_visible,
    coalesce(elem->>'status', 'APPROVED') as status,
    elem->>'datasheet' as datasheet,
    case 
      when elem->'specifications' is null or jsonb_typeof(elem->'specifications') = 'null' then '{}'::jsonb 
      else elem->'specifications' 
    end as specifications,
    elem->>'metaTitle' as meta_title,
    elem->>'metaDescription' as meta_description,
    elem->>'indentTime' as indent_time,
    coalesce(elem->>'stockStatus', 'INDENT') as stock_status,
    (elem->>'createdAt')::timestamptz as shop_created_at,
    (elem->>'updatedAt')::timestamptz as shop_updated_at,
    'SHOP_API' as source,
    now() as synced_at,
    now() as updated_at
  from jsonb_array_elements(products_json) as elem
  where (elem->>'sku' is not null and trim(elem->>'sku') != '')
     or (elem->>'item_no' is not null and trim(elem->>'item_no') != '')
  on conflict (item_no) do update set
    shop_id = excluded.shop_id,
    sku = excluded.sku,
    item_name = coalesce(excluded.item_name, accurate_items.item_name),
    description = excluded.description,
    long_description = excluded.long_description,
    unit_price = excluded.unit_price,
    base_price = excluded.base_price,
    available_to_sell = excluded.available_to_sell,
    brand = excluded.brand,
    category = excluded.category,
    image = excluded.image,
    slider_images = excluded.slider_images,
    accurate_id = excluded.accurate_id,
    item_type = excluded.item_type,
    is_visible = excluded.is_visible,
    status = excluded.status,
    datasheet = excluded.datasheet,
    specifications = excluded.specifications,
    meta_title = excluded.meta_title,
    meta_description = excluded.meta_description,
    indent_time = excluded.indent_time,
    stock_status = excluded.stock_status,
    shop_created_at = excluded.shop_created_at,
    shop_updated_at = excluded.shop_updated_at,
    source = 'SHOP_API',
    synced_at = now(),
    updated_at = now();

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;
