-- Create table for Accurate Items Catalog
create table if not exists accurate_items (
  id bigint primary key generated by default as identity,
  item_no text not null unique,
  item_name text,
  unit_name text default 'Pcs',
  unit_price numeric default 0,
  stock_quantity numeric default 0,
  available_to_sell numeric default 0,
  category text,
  brand text default 'SIEMENS',
  specs jsonb default '{}'::jsonb,
  source text default 'ACCURATE',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Indexes for accurate_items
create index if not exists idx_accurate_items_item_no on accurate_items (item_no);
create index if not exists idx_accurate_items_category on accurate_items (category);
create index if not exists idx_accurate_items_search on accurate_items using gin(
  to_tsvector('english', coalesce(item_no, '') || ' ' || coalesce(item_name, '') || ' ' || coalesce(category, ''))
);

-- Enable RLS on accurate_items
alter table accurate_items enable row level security;

drop policy if exists "Allow read access for authenticated users on accurate_items" on accurate_items;
create policy "Allow read access for authenticated users on accurate_items" 
  on accurate_items for select using (auth.role() = 'authenticated');

drop policy if exists "Allow write access for authenticated users on accurate_items" on accurate_items;
create policy "Allow write access for authenticated users on accurate_items" 
  on accurate_items for all using (auth.role() = 'authenticated');

-- Create table for Custom Component Converter Rules (Overrides & Manual Mappings)
create table if not exists converter_custom_rules (
  id uuid primary key default gen_random_uuid(),
  source_brand text not null, -- 'SCHNEIDER' | 'ABB' | 'OTHER'
  source_model text not null,
  category text,
  target_siemens_mlfb text not null,
  target_siemens_name text,
  spec_match_notes text,
  match_confidence integer default 100,
  created_by text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Index on converter_custom_rules
create index if not exists idx_converter_rules_brand on converter_custom_rules (source_brand);
create index if not exists idx_converter_rules_source_model on converter_custom_rules (source_model);

-- Enable RLS on converter_custom_rules
alter table converter_custom_rules enable row level security;

drop policy if exists "Allow read access on converter_custom_rules" on converter_custom_rules;
create policy "Allow read access on converter_custom_rules" 
  on converter_custom_rules for select using (auth.role() = 'authenticated');

drop policy if exists "Allow write access on converter_custom_rules" on converter_custom_rules;
create policy "Allow write access on converter_custom_rules" 
  on converter_custom_rules for all using (auth.role() = 'authenticated');

-- Seed accurate_items from existing accurate_purchase_order_items and accurate_delivery_order_items
insert into accurate_items (item_no, item_name, unit_name, unit_price, category, source)
select distinct on (item_code)
  item_code as item_no,
  item_name,
  coalesce(unit_name, 'Pcs') as unit_name,
  coalesce(unit_price, 0) as unit_price,
  case 
    when item_code ~* '^(5SL|5SY|5SJ|5SP|5TJ)' then 'MCB'
    when item_code ~* '^(3VA|3VJ|3VM|3VL|3VT)' then 'MCCB'
    when item_code ~* '^(3WL|3WA|3WT|3WN)' then 'ACB'
    when item_code ~* '^(3RT|3TF|3TG|3TS)' then 'CONTACTOR'
    when item_code ~* '^(3RU|3RB)' then 'TOR'
    when item_code ~* '^(3RV)' then 'MPCB'
    when item_code ~* '^(3RW)' then 'SOFT_STARTER'
    when item_code ~* '^(6SL|6SE|6AU|V20|G120)' then 'VFD'
    when item_code ~* '^(3SU|3SB|3SE)' then 'PILOT_DEVICE'
    when item_code ~* '^(6EP|6ES7148)' then 'POWER_SUPPLY'
    when item_code ~* '^(6ED1|6ES7)' then 'PLC_AUTOMATION'
    when item_code ~* '^(5SD|5TT)' then 'SPD_MODULAR'
    when item_code ~* '(ACC|SWITCH|TERMINAL|RELAY)' then 'ACCESSORIES'
    else 'OTHER'
  end as category,
  'PO_HISTORY' as source
from accurate_purchase_order_items
where item_code is not null and trim(item_code) != ''
on conflict (item_no) do update set
  item_name = coalesce(excluded.item_name, accurate_items.item_name),
  unit_price = case when excluded.unit_price > 0 then excluded.unit_price else accurate_items.unit_price end,
  category = coalesce(excluded.category, accurate_items.category),
  updated_at = now();

insert into accurate_items (item_no, item_name, unit_name, category, source)
select distinct on (item_code)
  item_code as item_no,
  item_name,
  coalesce(unit_name, 'Pcs') as unit_name,
  case 
    when item_code ~* '^(5SL|5SY|5SJ|5SP|5TJ)' then 'MCB'
    when item_code ~* '^(3VA|3VJ|3VM|3VL|3VT)' then 'MCCB'
    when item_code ~* '^(3WL|3WA|3WT|3WN)' then 'ACB'
    when item_code ~* '^(3RT|3TF|3TG|3TS)' then 'CONTACTOR'
    when item_code ~* '^(3RU|3RB)' then 'TOR'
    when item_code ~* '^(3RV)' then 'MPCB'
    when item_code ~* '^(3RW)' then 'SOFT_STARTER'
    when item_code ~* '^(6SL|6SE|6AU|V20|G120)' then 'VFD'
    when item_code ~* '^(3SU|3SB|3SE)' then 'PILOT_DEVICE'
    when item_code ~* '^(6EP|6ES7148)' then 'POWER_SUPPLY'
    when item_code ~* '^(6ED1|6ES7)' then 'PLC_AUTOMATION'
    when item_code ~* '^(5SD|5TT)' then 'SPD_MODULAR'
    when item_code ~* '(ACC|SWITCH|TERMINAL|RELAY)' then 'ACCESSORIES'
    else 'OTHER'
  end as category,
  'DO_HISTORY' as source
from accurate_delivery_order_items
where item_code is not null and trim(item_code) != ''
on conflict (item_no) do update set
  item_name = coalesce(excluded.item_name, accurate_items.item_name),
  updated_at = now();
